.PHONY: run
run: 
	python3 manage.py runserver

.PHONY: db/migrations/migrate
db/migrations/migrate:
	python3 manage.py migrate

.PHONY: db/migrations/make
db/migrations/make:
	python3 manage.py makemigrations